// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-songs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-songs.ts
var search_songs_default = defineTool({
  name: "search_songs",
  title: "Search songs",
  description: "Search the music library by song title, artist, or album.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to match against title, artist, or album."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const pattern = `%${query.replace(/[%_]/g, "")}%`;
    const { data, error } = await supabase.from("songs").select("id, title, artist, album, duration").or(`title.ilike.${pattern},artist.ilike.${pattern},album.ilike.${pattern}`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { songs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-playlists.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_playlists_default = defineTool2({
  name: "list_playlists",
  title: "List playlists",
  description: "List the signed-in user's playlists, newest first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max playlists (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("playlists").select("id, name, description, is_public, play_count, created_at").eq("owner_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { playlists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-playlist-songs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_playlist_songs_default = defineTool3({
  name: "get_playlist_songs",
  title: "Get playlist songs",
  description: "List the songs inside a playlist the signed-in user can access.",
  inputSchema: {
    playlist_id: z3.string().uuid().describe("The playlist id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ playlist_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("playlist_songs").select("position, songs(id, title, artist, album, duration)").eq("playlist_id", playlist_id).order("position", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const songs = (data ?? []).map((row) => ({
      position: row.position,
      ...row.songs
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(songs) }],
      structuredContent: { songs }
    };
  }
});

// src/lib/mcp/tools/create-playlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var create_playlist_default = defineTool4({
  name: "create_playlist",
  title: "Create playlist",
  description: "Create a new playlist owned by the signed-in user.",
  inputSchema: {
    name: z4.string().trim().min(1).max(120).describe("Playlist name."),
    description: z4.string().trim().max(500).optional().describe("Optional description."),
    is_public: z4.boolean().optional().describe("Make the playlist publicly discoverable.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, description, is_public }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("playlists").insert({
      owner_id: ctx.getUserId(),
      name,
      description: description ?? null,
      is_public: is_public ?? false
    }).select("id, name, description, is_public").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { playlist: data }
    };
  }
});

// src/lib/mcp/tools/add-song-to-playlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var add_song_to_playlist_default = defineTool5({
  name: "add_song_to_playlist",
  title: "Add song to playlist",
  description: "Append an existing song to one of the signed-in user's playlists.",
  inputSchema: {
    playlist_id: z5.string().uuid().describe("Target playlist id."),
    song_id: z5.string().uuid().describe("Song id to add.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ playlist_id, song_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: last } = await supabase.from("playlist_songs").select("position").eq("playlist_id", playlist_id).order("position", { ascending: false }).limit(1).maybeSingle();
    const position = (last?.position ?? -1) + 1;
    const { data, error } = await supabase.from("playlist_songs").insert({ playlist_id, song_id, position }).select("playlist_id, song_id, position").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hxqdbfehpwsmvnlpqgsa";
var mcp_default = defineMcp({
  name: "harmony-hub",
  title: "Harmony Hub",
  version: "0.1.0",
  instructions: "Tools for Harmony Hub, a music streaming app. Search the song library, browse the signed-in user's playlists, read playlist contents, create playlists, and add songs to them.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_songs_default,
    list_playlists_default,
    get_playlist_songs_default,
    create_playlist_default,
    add_song_to_playlist_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
